[window]
padding = { x=5, y=5 }
dynamic_padding = true
decorations = "Buttonless"
dynamic_title  = true
option_as_alt = "Both"
opacity = 0.80


[font]
normal = { family = "Firacode Nerd Font" }

[keyboard]
bindings = [
		{ key = "Right", mods = "Option", chars = "\u001BF" },
		{ key = "Left", mods = "Option", chars = "\u001BB" },
]

# Colors (Gruvbox dark)
# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'


# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

